table 'Measures (2)'
	lineageTag: 60f9c1d1-a919-4b7e-a859-96c3235818d5

	measure 'Total Tests' = COUNTROWS(Fact_Hantavirus)
		formatString: 0
		lineageTag: 336afcb7-a98e-4ccd-9d1e-74f3a08a87b6

	measure 'Positive Cases' = SUM(Fact_Hantavirus[Hantavirus_Positive])
		formatString: 0
		lineageTag: ba53a0f8-bda2-48d9-8c3e-24c5c8473256

	measure 'Positivity Rate' =
			
			DIVIDE([Positive Cases], [Total Tests])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cc45073f-94e0-40b1-be82-eaafb7f0b107

	measure 'Severe Cases' =
			
			CALCULATE(
			    COUNTROWS(Fact_Hantavirus),
			    Fact_Hantavirus[Disease_Severity] = "Severe"
			)
		formatString: 0
		lineageTag: 9a83822f-e6f2-4986-8690-f60a5b29fe71

	measure 'Severe Case Rate' =
			
			DIVIDE([Severe Cases], [Positive Cases])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5f23521b-861a-4e68-a145-18fa3fdf13c0

	measure 'Average Symptom Count' =
			
			AVERAGE(Fact_Hantavirus[Symptom_Count])
		formatString: 0.00
		lineageTag: 6857ae85-d0e0-4435-8632-7c68780e7079

	measure 'High Immunological Risk Rate' =
			
			AVERAGE(Fact_Hantavirus[Immunological_Risk_Score])
		formatString: 0.00
		lineageTag: 916c6963-11db-4d50-9907-9502e78c6f04

	measure 'Rodent Exposure Cases' =
			
			CALCULATE(
			    [Positive Cases],
			    Fact_Hantavirus[Exposure_Type] = "Rodent Contact"
			)
		formatString: 0
		lineageTag: 1bcbe621-83de-4809-baf7-bb7af4b35e0c

	measure 'Rodent Exposure Rate' =
			
			DIVIDE([Rodent Exposure Cases], [Positive Cases])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cbc4087d-89fa-46b9-9345-c60845a5649f

	measure 'Positive Cases YTD' =
			
			TOTALYTD(
			    [Positive Cases],
			    Dim_Date[Sample_Date]
			)
		formatString: 0
		lineageTag: 6296ce37-bcea-419c-8983-7391ce1bc48e

	measure 'Positive Cases Previous Month' =
			
			CALCULATE(
			    [Positive Cases],
			    PREVIOUSMONTH(Dim_Date[Sample_Date])
			)
		formatString: 0
		lineageTag: bcfbf9ed-9ab5-4860-a0f2-a4f9d94811ca

	measure 'MoM Positive Cases Change %' =
			
			DIVIDE(
			    [Positive Cases] - [Positive Cases Previous Month],
			    [Positive Cases Previous Month]
			)
		lineageTag: d95219bc-ae1b-49c7-8bd6-d40ba05cfa0e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Severe High Risk Cases' =
			
			CALCULATE(
			    [Severe Cases],
			    Fact_Hantavirus[Immunological_Risk] = "High"
			)
		formatString: 0
		lineageTag: 0a40719e-3b3e-4c00-8c88-cb725c4fcdf0

	measure 'High Risk Positive Cases' =
			
			CALCULATE(
			    [Positive Cases],
			    Fact_Hantavirus[Immunological_Risk] = "High"
			)
		formatString: 0
		lineageTag: 6770a1db-77eb-4fd5-a85a-5a460aacb1fe

	measure 'Positive Rodent Contact Cases' =
			
			CALCULATE(
			    [Positive Cases],
			    Fact_Hantavirus[Exposure_Type] = "Rodent Contact"
			)
		formatString: 0
		lineageTag: 1e841b3e-4fed-492b-b4c3-f064ea23a810

	partition 'Measures (2)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

